import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';
import { KnowledgeArticleState } from '../../knowledge-articles/types/knowledge-article-state';

export enum NewsStatus {
  POSTED_WP = 'POSTED_WP',
  ERROR = 'ERROR',
  CRAWLED = 'CRAWLED',
}

@Schema({ timestamps: true })
export class NewsArticle extends Document {
  @Prop({ required: true })
  title: string;

  @Prop({ required: false })
  summary: string;

  @Prop({ required: false })
  importanceReason: string;

  @Prop({ required: false, enum: ['Rất cao', 'Cao', 'Trung bình'] })
  impactLevel: string;

  @Prop({ type: [String], required: false })
  targetAudience: string[];

  @Prop({ required: false })
  expertOpinion: string;

  @Prop({ required: false })
  publishDate: string;

  @Prop({ required: false })
  thumbnailUrl: string;

  @Prop({ required: false })
  source: string;

  @Prop({ required: false })
  url: string;

  @Prop({ type: [String], required: false })
  keywords: string[];

  @Prop({ required: true, unique: true, index: true })
  urlHash: string;

  @Prop({ type: Number, default: null })
  wpPostId: number;

  @Prop({ required: false })
  content: string;

  @Prop({ type: [String], enum: NewsStatus, default: [] })
  status: NewsStatus[];

  // === DEDUP FIELDS ===

  /** Vector embedding of title + summary (used as dedup candidate) */
  @Prop({ type: [Number], default: null })
  contentEmbedding: number[] | null;

  /** Text used to generate embedding */
  @Prop({ required: false })
  embeddingInput: string;

  /** Model used to generate embedding */
  @Prop({ required: false })
  embeddingModel: string;

  // === RETROACTIVE DEDUP MARKING ===

  /** Whether this article is a duplicate of an older article (retroactive scan) */
  @Prop({ default: false, index: true })
  isDuplicate: boolean;

  /** Reference to the original NewsArticle that this one duplicates */
  @Prop({ type: Types.ObjectId, default: null, index: true })
  duplicateOf: Types.ObjectId | null;

  /** Cosine similarity score against the original article */
  @Prop({ type: Number, default: null })
  duplicateScore: number | null;

  // ── Knowledge Articles Fields ──────────────────────────
  // Only populated when type === 'knowledge'. All optional.

  /** Discriminator: 'news' (default) | 'knowledge' */
  @Prop({ default: 'news', index: true })
  type: string;

  /** HTML-rendered content generated by AI writing step */
  @Prop({ type: String, default: null })
  htmlContent: string | null;

  /** Current pipeline state for knowledge articles */
  @Prop({ type: String, enum: KnowledgeArticleState, default: null })
  pipelineState: KnowledgeArticleState | null;

  /** Error message from the last failed pipeline step */
  @Prop({ type: String, default: null })
  pipelineError: string | null;

  /** Which pipeline step failed (1-5) */
  @Prop({ type: Number, default: null })
  pipelineFailedStep: number | null;

  /** WordPress category ID this article belongs to */
  @Prop({ type: Number, default: null })
  wpCategoryId: number | null;

  /** WordPress tag IDs applied to this article */
  @Prop({ type: [Number], default: [] })
  wpTagIds: number[];

  /** ID of the AI writing prompt config used */
  @Prop({ type: String, default: null })
  aiWritingPromptId: string | null;

  /** Featured image URL after generation */
  @Prop({ type: String, default: null })
  featuredImageUrl: string | null;

  /** WordPress media ID of the featured image */
  @Prop({ type: Number, default: null })
  wpMediaId: number | null;

  /** Array of inline image URLs generated for the article */
  @Prop({ type: [String], default: [] })
  inlineImageUrls: string[];

  /** Category slug used for rotation tracking */
  @Prop({ type: String, default: null })
  categorySlug: string | null;

  /** Batch ID linking articles generated in the same pipeline run */
  @Prop({ index: true, type: String, default: null })
  batchId: string | null;

  /** Soft delete timestamp — null means active */
  @Prop({ type: Date, default: null })
  deletedAt: Date | null;
}

export const NewsArticleSchema = SchemaFactory.createForClass(NewsArticle);

// === Dedup indexes ===
NewsArticleSchema.index({ publishDate: -1 });
NewsArticleSchema.index({ contentEmbedding: 1 }, { sparse: true });
NewsArticleSchema.index({ publishDate: -1, contentEmbedding: 1 }, { sparse: true });

// === Knowledge Article indexes ===
NewsArticleSchema.index({ type: 1, pipelineState: 1 });
NewsArticleSchema.index({ type: 1, batchId: 1 });
NewsArticleSchema.index({ type: 1, categorySlug: 1, createdAt: -1 });
